// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0iJEKSl7XowvFw2y5Ne6XoJm-wgxd7tI',
    appId: '1:92301455203:web:5e1527b0589899c374ad56',
    messagingSenderId: '92301455203',
    projectId: 'spotify-dec51',
    authDomain: 'spotify-dec51.firebaseapp.com',
    storageBucket: 'spotify-dec51.appspot.com',
    measurementId: 'G-KZ07R8L4J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIt9ZRuLckZCNAMn264CfvVH67RTlpkCI',
    appId: '1:92301455203:android:5b57b5a29322b33174ad56',
    messagingSenderId: '92301455203',
    projectId: 'spotify-dec51',
    storageBucket: 'spotify-dec51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ8OQms_E2GFQdj8hQKcoi0RD4wxi24gg',
    appId: '1:92301455203:ios:075ab4190eed080f74ad56',
    messagingSenderId: '92301455203',
    projectId: 'spotify-dec51',
    storageBucket: 'spotify-dec51.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxVrZplKcMWxF7L-XAdQzBW7f5PJx1p1s',
    appId: '1:44302975505:ios:39fa40ee9564bf2dbfe7b0',
    messagingSenderId: '44302975505',
    projectId: 'spotifyclone-8a5a0',
    storageBucket: 'spotifyclone-8a5a0.appspot.com',
    iosBundleId: 'com.example.spotifyclone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCeOS-gze2ZeonTlvV9Ai2NpkAsDh7QiLc',
    appId: '1:44302975505:web:7eba6229b62d0ad4bfe7b0',
    messagingSenderId: '44302975505',
    projectId: 'spotifyclone-8a5a0',
    authDomain: 'spotifyclone-8a5a0.firebaseapp.com',
    storageBucket: 'spotifyclone-8a5a0.appspot.com',
    measurementId: 'G-71VXS2LZD6',
  );

}